/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 15
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 640
      image_height: 480
      camera_name: "logitech"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: false
      white_balance: 4000
      autoexposure: false
      exposure: 100
      autofocus: false
      focus: -1

  # parameters = [{'camera_name':         'logitech'},
  #               {'video_device':        '/dev/video0'},
  #               {'pixel_format':        'yuyv2rgb'},
  #               {'image_width':         640},
  #               {'image_height':        480},
  #               {'framerate':           15.0},
  #               {'brightness':          -1},
  #               {'contrast':            -1},
  #               {'saturation':          -1},
  #               {'sharpness':           -1},
  #               {'gain':                -1},
  #               {'auto_white_balance':  False},
  #               {'white_balance':       4000},
  #               {'autoexposure':        False},
  #               {'exposure':            100},
  #               {'autofocus':           True},
  #               {'focus':               -1}])

# old yaml file stuff
# /**:
#     ros__parameters:
#       video_device: "/dev/video0"
#       framerate: 30.0
#       io_method: "mmap"
#       frame_id: "camera"
#       pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
#       av_device_format: "YUV422P"
#       image_width: 640
#       image_height: 480
#       camera_name: "test_camera"
#       camera_info_url: "package://usb_cam/config/camera_info.yaml"
#       brightness: -1
#       contrast: -1
#       saturation: -1
#       sharpness: -1
#       gain: -1
#       auto_white_balance: false
#       white_balance: 4000
#       autoexposure: true
#       exposure: 100
#       autofocus: false
#       focus: -1